/*
 * board_config.h
 *
 *  Created on: 24. 8. 2018
 *      Author: Petr
 */

#ifndef BSP_BOARD_CONFIG_H_
#define BSP_BOARD_CONFIG_H_

#include "chip.h"

#define DEVEL_BOARD

#define TERMINAL_ID 1

#define CARD_READER1 0
#define CARD_READER1_ID 1
#define CARD_READER1_PORT 1
#define CARD_READER1_D0_PIN 1
#define CARD_READER1_D1_PIN 2
#define CARD_READER1_RELAY_PORT 0
#define CARD_READER1_RELAY_PIN 0

#define CARD_READER2 0
#define CARD_READER2_ID 2
#define CARD_READER2_PORT 2
#define CARD_READER2_D0_PIN 0
#define CARD_READER2_D1_PIN 0
#define CARD_READER2_RELAY_PORT 0
#define CARD_READER2_RELAY_PIN 0

#define CARD_READER3 1
#define CARD_READER3_ID 3
#define CARD_READER3_PORT 3
#define CARD_READER3_D0_PIN 1
#define CARD_READER3_D1_PIN 2
#define CARD_READER3_RELAY_PORT 0
#define CARD_READER3_RELAY_PIN 0

#define CARD_READER_BEEPER_PORT 0
#define CARD_READER_BEEPER_PIN 0

#define CARD_READER_LED_PORT 0
#define CARD_READER_LED_PIN 0

#define CARD_READERS_MAX_COUNT 4
//#define CARD_READERS_COUNT (CARD_READER1 + CARD_READER2 + CARD_READER3)

#endif /* BSP_BOARD_CONFIG_H_ */
